name: EnskDeInputSkinWithJpn
author: Ensk

fontFace:
  #图标字体
  - url: kafei.ttf

# 中文键盘
pinyin:
  iPhone:
    portrait: pinyin_9_portrait
    landscape: pinyin_26_portrait
  iPad:
    portrait: pinyin_26_portrait
    landscape: pinyin_26_portrait
    floating: pinyin_26_portrait

# 日语键盘
japanese:
  iPhone:
    portrait: japanese_26_portrait
    landscape: japanese_26_portrait
  iPad:
    portrait: japanese_26_portrait
    landscape: japanese_26_portrait
    floating: japanese_26_portrait


# 英文键盘
alphabetic:
  iPhone:
    portrait: alphabetic_26_portrait
    landscape: alphabetic_26_portrait
  iPad:
    portrait: alphabetic_26_portrait
    landscape: alphabetic_26_portrait
    floating: alphabetic_26_portrait

# 数字键盘
numeric:
  iPhone:
    portrait: numeric_9_portrait
    landscape: numeric_9_portrait
  iPad:
    portrait: numeric_9_portrait
    landscape: numeric_9_portrait
    floating: numeric_9_portrait

# 符号键盘
symbolic:
  iPhone:
    portrait: symbolic_portrait
    landscape: symbolic_portrait
  iPad:
    portrait: symbolic_portrait
    landscape: symbolic_portrait
    floating: symbolic_portrait

# 设置浮动键盘
floatconfig:
  iPhone:
    portrait: floatconfig_portrait
    landscape: floatconfig_portrait

#表情键盘
emoji:
  iPhone:
    portrait: emoji_portrait
    landscape: emoji_portrait
  iPad:
    portrait: emoji_portrait
    landscape: emoji_portrait
    floating: emoji_portrait

keySounds:
  - inputKeySound: sounds/code.wav
  - deleteKeySound: sounds/del.wav
  - systemKeySound: sounds/code.wav
  - action: space
    url: sounds/space.wav
